name: Build Android APK

on: [push]

jobs:
  build:
    runs-on: ubuntu-20.04
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'
    
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
            python3-pip \
            git \
            zip \
            unzip \
            openjdk-11-jdk \
            zlib1g-dev \
            libffi-dev \
            libssl-dev
    
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install Cython==0.29.33 buildozer
    
    - name: Build APK with Buildozer
      run: |
        buildozer init
        cat > buildozer.spec << EOF
        [app]
        title = دانلودر من
        package.name = mydownloader
        package.domain = com.myapp
        version = 1.0
        source.dir = .
        source.main = main.py
        android.permissions = INTERNET,WRITE_EXTERNAL_STORAGE
        requirements = python3,flet
        android.api = 30
        android.minapi = 21
        EOF
        
        buildozer -v android debug
        
    - name: Upload APK artifact
      uses: actions/upload-artifact@v4
      with:
        name: app-apk
        path: bin/*.apk
